[package]
name = "ratatop"
version = "0.1.0"
edition = "2024"
default-run = "ratatop"

[dependencies]
color-eyre = "0.6.3"
crossterm = "0.28.1"
ratatui = "0.29.0"
sysinfo = "0.33.1"
tui-textarea = "0.7.0"
