[package]
name = "ratatop"
version = "0.1.0"
edition = "2024"
default-run = "ratatop"

[[bin]]
name = "ratatop"
path = "examples/final.rs"

[dependencies]
color-eyre = "0.6.3"
ratatui = "0.29.0"
sysinfo = "0.33.1"
